import type OpenAI from 'openai'

import type { OpenApiOperationMeta } from '../../shared/agent-types'

export type OpenAiTool = OpenAI.Chat.Completions.ChatCompletionFunctionTool
export type ChatMessage = OpenAI.Chat.Completions.ChatCompletionMessageParam

export interface ParsedToolBundle {
  tools: OpenAiTool[]
  operations: Map<string, OpenApiOperationMeta>
}

export type {
  AgentCommandInput,
  AgentCommandResult,
  AgentConfig,
  AgentConnectionIntentInput,
  AgentConnectionIntentResult,
  AgentEvent,
  AgentEventMeta,
  AgentLongTermMemory,
  AgentMemoryRecord,
  AgentMcpServerConfig,
  AgentMcpTransport,
  AgentMode,
  AgentStyle,
  AgentModelOption,
  AgentPathReference,
  AgentProviderConfig,
  AgentProviderModelConfig,
  AgentGenerateSopInput,
  AgentGenerateSopResult,
  AgentReloadRuntimeInput,
  AgentReloadRuntimeResult,
  AgentGenerateCaptureDraftInput,
  AgentGenerateCaptureDraftResult,
  AgentCommitCaptureDraftInput,
  AgentCommitCaptureDraftResult,
  CaptureKind,
  AgentRunInput,
  AgentSkillContext,
  AgentSkillInstallResult,
  AgentSkillOption,
  AgentSkillSearchResult,
  AgentExtensionOption,
  AgentExtensionCommand,
  AgentPiPackageSearchResult,
  AgentValidationResult,
  CommandApprovalDecision,
  CommandApprovalRequest,
  ExtensionUiDecision,
  ExtensionUiDismiss,
  ExtensionUiNotifyType,
  ExtensionUiRequest,
  CommandAuditResult,
  CommandRiskLevel,
  ConnectionConfig,
  ConnectionInput,
  ConnectionSource,
  HttpMethod,
  LocalFileWriter,
  LocalFileWriteResult,
  OpenApiOperationMeta,
  OperationRecord,
  PastedAttachmentInput,
  StoredAgentLogEntry,
  StoredAgentRun,
  SessionTokenUsage,
  OpsHistoryRating,
  OpsHistoryRecord,
  SubmitOpsFeedbackInput,
  SubmitOpsFeedbackResult,
  UpdateOpsFeedbackInput,
  UpdateOpsFeedbackResult,
  TranscribeAudioInput,
  TranscribeAudioResult,
  TranscriptionSupportResult,
  StoredSessionHistoryDetail,
  StoredSessionHistoryItem,
  StoredSessionSummaryUpdate,
  StoredSessionTab,
  SubterminalCommandExecutor,
  TerminalCommandExecutor,
  TerminalCommandResult,
  ToolCatalogEntry,
  WikiDocument,
  WikiDocumentSummary,
  WikiSaveInput
} from '../../shared/agent-types'
